### ISSUE TITLE
Help needed with MNIST-DVS data preprocessing 

### ISSUE THREAD

**Issue by yeshwanthv5** [kclip/snn#1]
Hello @nskat 

I downloaded the MNIST-DVS dataset from http://www2.imse-cnm.csic.es/caviar/MNIST_DVS/ and executed the provided `process_mnist.m` to create processed data files.

```
On trying to run `process_mnist_dvs.py` on processed data I am getting the following error.
(venv) m-yeshwanth:data_preprocessing yesh$ python process_mnist_dvs.py 
train ../../datasets/MNIST-DVS/processed_mnist/processed_data1/scale4/mnist_1_scale04_0512.aedat
Traceback (most recent call last):
  File "process_mnist_dvs.py", line 227, in <module>
    make_mnist_dvs(path_to_data, path_to_hdf5, digits, max_pxl_value, min_pxl_value, T_max, window_length, scale, polarity, pattern, alphabet_size)
  File "process_mnist_dvs.py", line 178, in make_mnist_dvs
    window_length=window_length, polarity=polarity))
  File "/Users/yesh/venv/lib/python3.7/site-packages/tables/earray.py", line 219, in append
    self._check_shape_append(nparr)
  File "/Users/yesh/venv/lib/python3.7/site-packages/tables/earray.py", line 193, in _check_shape_append
    % (narank, self._v_pathname, myrank))
ValueError: the ranks of the appended object (4) and the ``/train/data`` EArray (3) differ
Closing remaining open files:../../datasets/mnist-dvs/mnist_dvs_10ms_26pxl_2_digits_polarity.hdf5...done
```

Please let me know how to fix it if this is a known issue.
Thanks in advance.

**Comment by nskat** [comment]
Hello,
Thanks for your question, may I ask which parameters you used when encountering this issue?

**Comment by yeshwanthv5** [comment]
I used the default parameters. Only changed the path to data.
```
path_to_data = r'../../datasets/MNIST-DVS/processed_mnist'

# path_to_data = r'path/to/mnist-dvs/processed_polarity'
# path_to_data = r'C:\Users\K1804053\Desktop\PhD\Federated SNN\processed_polarity'

# digits to consider
digits = [1, 7]

# Pixel values to consider
max_pxl_value = 73
min_pxl_value = 48

T_max = int(2e6)  # maximum duration of an example in us
window_length = 10000

scale = 'scale4'
polarity = True
alphabet_size = 2
pattern = [1]
```

**Comment by nskat** [comment]
Hello @yeshwanthv5,
Thank you for bringing this to my attention and sorry for the slow response, it should now be fixed.

**Comment by yeshwanthv5** [comment]
Thanks a lot @nskat, the script is working now.
